name: 'wu1project'
version: '1.0.0'
config-version: 2

profile: 'wu1project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  wu1project:
    enabled: true
    materialized: view
    public:
      materialized: view
      schema: public
      tags: ["public"]


  
